name: Create Pull Request to other repo

on: [pull_request]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: walk8243/nodejs-terminal
      - run: ls
