name: Create Pull Request to other repo

on: [pull_request]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh workflow run main.yml --repo walk8243/nodejs-terminal \
            -f version=0.9.0 \
            -f sha256=${{ github.event.pull_request.head.sha }}
    env:
      GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
