name: sed command test

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: replace cask
        run: |
          cask=$(cat test.rb)
          format(${{ env.cask }}, '1.2.3', '37cbd6615440141386697092587c4a7702d1d79a')
