name: sed command test

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: format($(cat test.rb), '1.2.3', '37cbd6615440141386697092587c4a7702d1d79a')
