name: sed command test

on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sed -i -e 's/version .+/version "1.2.3"/g' test.rb
      - run: cat test.rb
